# Generated by Django 4.2.7 on 2023-11-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('due_time', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='task_images/')),
                ('importance', models.CharField(default='pas_urgent', max_length=20)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
    ]
